// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-stations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-stations.ts
var list_stations_default = defineTool({
  name: "list_stations",
  title: "List stations",
  description: "List stations with status, date and who filled them in, optionally filtered by name or status.",
  inputSchema: {
    search: z.string().optional().describe("Part of the station name to search for."),
    status: z.string().optional().describe("Status filter, e.g. 'in uitvoering', 'opgeleverd', 'goedgekeurd'."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum number of results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }) => {
    let q = supabaseAnon().from("stations").select("id, naam_msr, behuizingsnummer, type_ruimte, ingevuld_door, datum, status, opdrachtgever, submitted_at").order("datum", { ascending: false }).limit(limit ?? 50);
    if (search) q = q.ilike("naam_msr", `%${search}%`);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const stations = (data ?? []).map((s) => ({
      id: s.id,
      naam: s.naam_msr,
      behuizingsnummer: s.behuizingsnummer,
      type: s.type_ruimte,
      ingevuld_door: s.ingevuld_door,
      datum: s.datum,
      status: s.status,
      opdrachtgever: s.opdrachtgever,
      opgeleverd_op: s.submitted_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(stations) }], structuredContent: { stations } };
  }
});

// src/lib/mcp/tools/get-station.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_station_default = defineTool2({
  name: "get_station",
  title: "Get station details",
  description: "Get one station with its photos per category, skipped (NVT) tasks with reasons, and notes.",
  inputSchema: { id: z2.string().uuid().describe("Station id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const sb = supabaseAnon();
    const [st, fotos, skips, notes] = await Promise.all([
      sb.from("stations").select("*").eq("id", id).maybeSingle(),
      sb.from("fotos").select("categorie, url, uploaded_at, review_status, review_reden").eq("station_id", id),
      sb.from("categorie_skips").select("categorie, reden").eq("station_id", id),
      sb.from("categorie_opmerkingen").select("categorie, opmerking").eq("station_id", id)
    ]);
    const err = st.error ?? fotos.error ?? skips.error ?? notes.error;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    if (!st.data) throw new ToolError("Station not found");
    const s = st.data;
    const station = {
      id: s.id,
      naam: s.naam_msr,
      behuizingsnummer: s.behuizingsnummer,
      type: s.type_ruimte,
      ingevuld_door: s.ingevuld_door,
      datum: s.datum,
      status: s.status,
      opdrachtgever: s.opdrachtgever,
      fotos: (fotos.data ?? []).map((f) => ({
        categorie: f.categorie,
        url: f.url,
        uploaded_at: f.uploaded_at,
        review_status: f.review_status,
        review_reden: f.review_reden
      })),
      nvt: (skips.data ?? []).map((k) => ({ categorie: k.categorie, reden: k.reden })),
      opmerkingen: (notes.data ?? []).map((n) => ({ categorie: n.categorie, opmerking: n.opmerking }))
    };
    return { content: [{ type: "text", text: JSON.stringify(station) }], structuredContent: { station } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "to-foto-s",
  title: "TO Foto's",
  version: "0.1.0",
  instructions: "Read-only access to TO Foto's photo registrations for technical stations. Use `list_stations` to find stations, then `get_station` for photos, NVT tasks and notes.",
  tools: [list_stations_default, get_station_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
